home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    # ex: /home/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    # ex: /home/5/results/
    #path('<int:question_id>/results/', views.results, name='results'),
    # ex: /home/5/vote/
    #path('<int:question_id>/vote/', views.vote, name='vote'),
]

house/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /house/
    path('', views.index, name='index'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment'),
    # ex: /home/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    # ex: /home/5/results/
    #path('<int:question_id>/results/', views.results, name='results'),
    # ex: /home/5/vote/
    #path('<int:question_id>/vote/', views.vote, name='vote'),
]

project1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('house/', include('house.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('category/<int:id>/<slug:slug>/', views.category_houses, name='category'),
    path('house/<int:id>/<slug:slug>/', views.house_detail, name='house_detail'),
    path('search/', views.house_search, name='house_search'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('sss/', views.faq, name='faq'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=255)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=255)
    address = models.CharField(blank=True, max_length=255)
    phone = models.CharField(blank=True, max_length=255)
    fax = models.CharField(blank=True, max_length=255)
    email = models.CharField(blank=True, max_length=255)
    smtpserver = models.CharField(blank=True, max_length=255)
    smtpemail = models.CharField(blank=True, max_length=255)
    smtppassword = models.CharField(blank=True, max_length=255)
    smtpport = models.CharField(blank=True, max_length=255)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=255)
    instagram = models.CharField(blank=True, max_length=255)
    twitter = models.CharField(blank=True, max_length=255)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(blank=True, max_length=70)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': TextInput(attrs={'class': 'controls', 'placeholder': 'Full Name'}),
            'email': TextInput(attrs={'class': 'controls', 'placeholder': 'Email Address'}),
            'subject': TextInput(attrs={'class': 'controls', 'placeholder': 'Subject'}),
            'message': Textarea(attrs={'class': 'controls', 'placeholder': 'Message'}),
        }


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=70)
    country = models.CharField(blank=True, max_length=70)
    image = models.ImageField(blank=True, upload_to='images/users')

    def user_name(self):
        return self.user.first_name + ' ' + self.user.last_name + ' [ ' + self.user.username + ' ] '

    def image_tag(self):
        return mark_safe('<img src="{}" height="50" />'.format(self.image.url))
    image_tag.short_description = 'Image'


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'address', 'city', 'country', 'image']


class Faq(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    orderNumber = models.IntegerField()
    question = models.CharField(max_length=255)
    answer = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

house/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.forms import ModelForm
from django.urls import reverse
from django.utils.safestring import mark_safe
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class Category(MPTTModel):
    STATUS = (
        ('True','Evet'),
        ('False','Hayır'),
    )
    title = models.CharField(max_length=100)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' / '.join(full_path[::-1])

    def image_tag(self):
        return mark_safe('<img src="{}" height="50" />'.format(self.image.url))
    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class House(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(blank=True, max_length=255)
    keywords = models.CharField(blank=True, max_length=255)
    description = models.CharField(blank=True, max_length=255)
    slug = models.SlugField(null=False, unique=True)
    image = models.ImageField(blank=True, upload_to='images/')
    rent = models.IntegerField(blank=True)
    detail = RichTextUploadingField(blank=True)
    status = models.CharField(blank=True, max_length=10, choices=STATUS)
    create_at = models.DateTimeField(blank=True, auto_now_add=True)
    update_at = models.DateTimeField(blank=True, auto_now=True)
    area = models.IntegerField(blank=True, )
    location = models.CharField(blank=True, max_length=255)
    room = models.CharField(blank=True, max_length=255)
    buildingFloor = models.IntegerField(blank=True, )
    floorLocation = models.IntegerField(blank=True, )
    furnished = models.CharField(blank=True, max_length=10, choices=STATUS)
    balconied = models.CharField(blank=True, max_length=10, choices=STATUS)
    heating = models.CharField(blank=True, max_length=255)
    withintheSite = models.CharField(blank=True, max_length=10, choices=STATUS)
    fromWho = models.CharField(blank=True, max_length=255)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50" />'.format(self.image.url))
    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('house_detail', kwargs={'slug': self.slug})


class Images(models.Model):
    house = models.ForeignKey(House, on_delete=models.CASCADE)
    title = models.CharField(blank=True, max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50" />'.format(self.image.url))
    image_tag.short_description = 'Image'


class Comment(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('True', 'Evet'),
        ('False', 'Hayır')
    )
    house = models.ForeignKey(House, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(blank=True, max_length=50)
    comment = models.CharField(blank=True, max_length=255)
    status = models.CharField(blank=True, max_length=10, choices=STATUS)
    ip = models.CharField(blank=True, max_length=20)
    create_at = models.DateTimeField(blank=True, auto_now_add=True)
    update_at = models.DateTimeField(blank=True, auto_now=True)

    def __str__(self):
        return self.subject


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment']

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    query = forms.CharField(max_length=100, label='Search')


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, label='User Name :')
    email = forms.EmailField(max_length=200, label='Email :')
    first_name = forms.CharField(max_length=100, help_text='First Name', label='First Name :')
    last_name = forms.CharField(max_length=100, help_text='Last Name', label='Last Name :')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

home/views.py
import json

from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from home.forms import SearchForm, SignUpForm
from home.models import Setting, ContactFormMessage, ContactFormu, UserProfile, Faq
from house.models import House, Category, Images, Comment


def index(request):
    setting = Setting.objects.get(pk=1)
    slider_data = House.objects.all()[:3]
    category = Category.objects.all()
    random_houses = House.objects.all()[:6]
    last_houses = House.objects.all().order_by('-id')[:6]
    context = {'setting': setting,
               'slider_data': slider_data,
               'page': 'home',
               'category': category,
               'random_houses': random_houses,
               'last_houses': last_houses,
               }
    return render(request, 'index.html', context)



def hakkimizda(request):
    setting = Setting.objects.get(pk=1)
    context = {'setting': setting}
    return render(request, 'hakkimizda.html', context)


def referanslar(request):
    setting = Setting.objects.get(pk=1)
    context = {'setting': setting}
    return render(request, 'referanslar.html', context)


def iletisim(request):
    if request.method == 'POST':
        form = ContactFormu(request.POST)
        if form.is_valid():
            data = ContactFormMessage()
            data.name = form.cleaned_data['name']
            data.email = form.cleaned_data['email']
            data.subject = form.cleaned_data['subject']
            data.message = form.cleaned_data['message']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request, "Mesajınız başarıyla gönderilmiştir.")
            return HttpResponseRedirect('/iletisim')

    setting = Setting.objects.get(pk=1)
    form = ContactFormu()
    context = {'setting': setting, 'form': form}
    return render(request, 'iletisim.html', context)


def category_houses(request, id, slug):
    houses = House.objects.filter(category_id=id)
    category = Category.objects.all()
    categoryData = Category.objects.get(pk=id)
    context = {'houses': houses, 'category': category, 'categoryData': categoryData}
    return render(request, 'houses.html', context)


def house_detail(request, id, slug):
    category = Category.objects.all()
    house = House.objects.get(pk=id)
    images = Images.objects.filter(house_id=id)
    comments = Comment.objects.filter(house_id=id, status='True')
    context = {'house': house,
               'category': category,
               'images': images,
               'comments': comments}
    return render(request, 'house_detail.html', context)


def house_search(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            category = Category.objects.all()
            query = form.cleaned_data['query']
            houses = House.objects.filter(title__icontains=query)
            context = {'houses': houses,
                       'category': category,
                       }
            return render(request, 'house_search.html', context)
    return HttpResponseRedirect('/')


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return HttpResponseRedirect('/')
        else:
            # Return an 'invalid login' error message.
            messages.warning(request, "Login Hatası! Kullanıcı adı veya şifre yanlış")
            return HttpResponseRedirect('/login')
    category = Category.objects.all()
    context = {'category': category}
    return render(request, 'login.html', context)


def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            current_user = request.user
            data = UserProfile()
            data.user_id = current_user.id
            data.image = "images/users/user.jpg"
            data.save()
            return HttpResponseRedirect('/')

    form = SignUpForm()
    category = Category.objects.all()
    context = {'category': category,
               'form': form}
    return render(request, 'signup.html', context)


def faq(request):
    category = Category.objects.all()
    faq = Faq.objects.all().order_by('orderNumber')
    context = {'category': category,
               'faq': faq
               }
    return render(request, 'sss.html', context)

house/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from house.models import CommentForm, Comment


def index(request):
    return HttpResponse("House Page")


@login_required(login_url='/login')
def addcomment(request, id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            current_user = request.user
            data = Comment()
            data.user_id = current_user.id
            data.house_id = id
            data.subject = form.cleaned_data['subject']
            data.comment = form.cleaned_data['comment']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request, "Yorumunuz başarıyla gönderilmiştir.")
            url = request.META.get('HTTP_REFERER')
            return HttpResponseRedirect(url)

    messages.warning(request, "Yorumunuz kaydedilmedi.Lütfen kontrol ediniz.")
    return HttpResponse("Kaydedilme işlemi gerçekleşmedi.")

home/templates/footer.html
{% load static %}   <!--footer starts from here-->
    <footer class="footer">
        <div class="container bottom_border">
            <div class="row">
				<div class="col-lg-3 col-md-6 col-sm-6 col">
					<h5 class="headin5_amrc col_white_amrc pt2">About Us</h5>
					<!--headin5_amrc-->
					<p class="mb10">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
					<ul class="footer-social">
						<li><a class="facebook hb-xs-margin" href="#"><span class="hb hb-xs spin hb-facebook"><i class="fab fa-facebook-f"></i></span></a></li>
						<li><a class="twitter hb-xs-margin" href="#"><span class="hb hb-xs spin hb-twitter"><i class="fab fa-twitter"></i></span></a></li>
						<li><a class="instagram hb-xs-margin" href="#"><span class="hb hb-xs spin hb-instagram"><i class="fab fa-instagram"></i></span></a></li>
						<li><a class="googleplus hb-xs-margin" href="#"><span class="hb hb-xs spin hb-google-plus"><i class="fab fa-google-plus-g"></i></span></a></li>
						<li><a class="dribbble hb-xs-margin" href="#"><span class="hb hb-xs spin hb-dribbble"><i class="fab fa-dribbble"></i></span></a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6">
					<h5 class="headin5_amrc col_white_amrc pt2">Quick links</h5>
					<!--headin5_amrc-->
					<ul class="footer_ul_amrc">
						<li><a href="#"><i class="fas fa-long-arrow-alt-right"></i>Default Version</a></li>
						<li><a href="#"><i class="fas fa-long-arrow-alt-right"></i>Boxed Version</a></li>
						<li><a href="#"><i class="fas fa-long-arrow-alt-right"></i>Our Team </a></li>
						<li><a href="#"><i class="fas fa-long-arrow-alt-right"></i>About Us</a></li>
						<li><a href="#"><i class="fas fa-long-arrow-alt-right"></i>Our Services</a></li>
						<li><a href="#"><i class="fas fa-long-arrow-alt-right"></i>Get In Touch</a></li>
					</ul>
					<!--footer_ul_amrc ends here-->
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 col">
					<h5 class="headin5_amrc col_white_amrc pt2">Follow us</h5>
					<!--headin5_amrc ends here-->
					<ul class="footer_ul2_amrc">
						<li>
							<a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a>
							<p>Lorem Ipsum is simply dummy...<a href="#">https://www.lipsum.com/</a></p>
						</li>
						<li>
							<a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a>
							<p>Lorem Ipsum is simply dummy...<a href="#">https://www.lipsum.com/</a></p>
						</li>
						<li>
							<a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a>
							<p>Lorem Ipsum is simply dummy...<a href="#">https://www.lipsum.com/</a></p>
						</li>
					</ul>
					<!--footer_ul2_amrc ends here-->
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 ">
					<div class="news-box">
						<h5 class="headin5_amrc col_white_amrc pt2">Newsletter</h5>
						<p>Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...</p>
						<form action="#">
							<div class="input-group">
								<input class="form-control" placeholder="Search for..." type="text">
								<span class="input-group-btn">
								  <button class="btn btn-secondary" type="button">Go!</button>
								</span>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
        <div class="container">
            <p class="copyright text-center">All Rights Reserved. &copy; 2018 <a href="#">Zonebiz</a> Design By :
				<a href="https://html.design/">html design</a>
            </p>
        </div>
    </footer>

home/templates/header.html
<header class="slider-main">
    <div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
        <ol class="carousel-indicators">
            {% for slider in slider_data %}
                <li data-target="#carouselExampleIndicators" data-slide-to="{{ slider.id }}" class="{% if forloop.first %}active{% endif %}"></li>
            {% endfor %}
        </ol>
        <div class="carousel-inner" role="listbox">
            {% for slider in slider_data %}
                <div class="carousel-item{% if forloop.first %} active{% endif %}" style="background-image: url({{ slider.image.url }})">
                    <div class="carousel-caption d-none d-md-block">
                        <h3>{{ slider.title  }}</h3>
                        <p><a href="/house/{{ slider.id }}/{{ slider.slug }}">{{ slider.description }}</a></p>
                    </div>
                </div>
            {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</header>

home/templates/house_detail.html
{% extends "homebase.html" %}
{% block title %} {{ house.title }} {% endblock %}
{% block keywords %} {{ house.keywords }} {% endblock %}
{% block description %} {{ house.description }} {% endblock %}
{% block head %}
    {% load static %}
    <link rel="shortcut icon" type="text/x-icon" href="{{ setting.icon.url }}" >
    <link rel="stylesheet" href="{% static 'gallery/css/core-style.css' %}">
    <link rel="stylesheet" href="{% static 'gallery/style.css' %}">
{% endblock %}

{% block content %}

    <!-- full Title -->
    <div class="full-title">
        <div class="container">
            <!-- Page Heading/Breadcrumbs -->
            <h1 class="mt-4 mb-3"> Ev Detay </h1>
            <div class="breadcrumb-main">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="/">Home</a>
                    </li>
                    <li class="breadcrumb-item active">Ev Detay</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="blog-main">
        <div class="container">
            <div class="row">
                <!-- Post Content Column -->
                <div class="col-lg-8">
                    <!-- Preview Image -->
                    <div class="single_product_thumb">
                        <div id="product_details_slider" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li class="active" data-target="#product_details_slider" data-slide-to="0" style="background-image: url({{house.image.url}});">
                                </li>
                                {% for rs in images %}
                                    <li data-target="#product_details_slider" data-slide-to="{{ rs.id }}" style="background-image: url({{rs.image.url}});">
                                    </li>
                                {% endfor %}
                            </ol>
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <a class="gallery_img" href="#product_details_slider">
                                        <img class="d-block w-100" src="{{ house.image.url }}"  alt="slide">
                                    </a>
                                </div>
                                {% for rs in images %}
                                    <div class="carousel-item">
                                        <a class="gallery_img" href="#product_details_slider">
                                            <img class="d-block w-100" src="{{ rs.image.url }}"  alt="slide">
                                        </a>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="blog-right-side">
                        <!-- Comments Form -->
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <div class="card my-4">
                            <h5 class="card-header">Yorumunuz:</h5>
                            <div class="card-body">
                                <form action="/house/addcomment/{{ house.id }}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input class="form-control" type="text" name="subject" id="id_subject" placeholder="Konu" />
                                    </div>
                                    <div class="form-group">
                                        <textarea class="form-control" name="comment" id="id_comment" rows="3" placeholder="Yorum"></textarea>
                                    </div>
                                    {% if user.id is not None %}
                                        <button type="submit" class="btn btn-primary">Gönder</button>
                                    {% else %}
                                        Yorum eklemek için giriş yapınız!
                                    {% endif %}
                                </form>
                            </div>
                        </div>
                    </div>

                    {% for rs in comments %}
                    <!-- Single Comment -->
                    <div class="media mb-4">
                        <div class="media-body">
                            <div><h5 class="mt-0">{{ rs.user.username }}</h5></div>
                            <div><h5 class="mt-0">{{ rs.create_at }}</h5></div>
                            <div><h3 class="mt-0">{{ rs.subject }}</h3></div>
                            {{ rs.comment }}
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <!-- Sidebar Widgets Column -->
                <div class="col-md-4 blog-right-side">
                    <h3 class="my-3">Ev Bilgileri </h3>
                    <ul>
                        <li><span>Kategori :</span><span>{{ house.category }}</span></li>
                        <li><span>Oda :</span><span>{{ house.room }}</span></li>
                        <li><span>Alan :</span><span>{{ house.area }}</span></li>
                        <li><span>Kira :</span><span>{{ house.rent }}</span></li>
                        <li><span>Bulunduğu kat :</span><span>{{ house.floorLocation }}</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

home/templates/house_search.html
{% extends "homebase.html" %}

{% block title %} House Search Result {% endblock %}
{% block keywords %} {{ category.keywords }} {% endblock %}
{% block description %} {{ category.description }} {% endblock %}
{% block head %}
    <link rel="shortcut icon" type="text/x-icon" href="{{ setting.icon.url }}" >
{% endblock %}
{% block content %}

    <!-- full Title -->
    <div class="full-title">
        <div class="container">
            <!-- Page Heading/Breadcrumbs -->
            <div class="breadcrumb-main">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="/">Home</a>
                    </li>
                    <li class="breadcrumb-item active"> {{ category.title }} </li>
                </ol>
            </div>
        </div>
    </div>
    <div class="portfolio-col">
        <div class="container">
            <div class="row">
                <table cellpadding="3" width="1200">
                    <tr>
                        <th>Image</th>
                        <th>House Name</th>
                        <th>Category</th>
                        <th>Rent</th>
                    </tr>
                    {% for rs in houses %}
                        <tr>
                            <td><a href="/house/{{ rs.id }}/{{ rs.slug }}"><img src="{{ rs.image.url }}" style="width:255px;height:258.953px" alt=""/></a></td>
                            <td><h4 class="house-name"><a href="/house/{{ rs.id }}/{{ rs.slug }}">{{ rs.title }}</a></h4></td>
                            <td><a href="/category/{{ rs.category.id }}/{{ rs.category.slug }}">{{ rs.category }}</a></td>
                            <td><h4>{{ rs.rent }}</h4></td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}