home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    # ex: /home/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    # ex: /home/5/results/
    #path('<int:question_id>/results/', views.results, name='results'),
    # ex: /home/5/vote/
    #path('<int:question_id>/vote/', views.vote, name='vote'),
]

project1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('house/', include('house.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('category/<int:id>/<slug:slug>/', views.category_houses, name='category'),
    path('house/<int:id>/<slug:slug>/', views.house_detail, name='house_detail'),
    path('search/', views.house_search, name='house_search'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('sss/', views.faq, name='faq'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /house/
    path('', views.index, name='index'),
    path('update/', views.user_update, name='user_update'),
    path('password/', views.change_password, name='change_password'),
    path('comments/', views.comments, name='comments'),
    path('delete_comment/<int:id>', views.delete_comment, name='delete_comment'),
    path('addhouse/', views.addhouse, name='addhouse'),
    path('edithouse/<int:id>', views.edithouse, name='edithouse'),
    path('deletehouse/<int:id>', views.deletehouse, name='deletehouse'),
    path('houses/', views.houses, name='houses'),
    path('houseaddimage/<int:id>', views.houseaddimage, name='houseaddimage'),

    # ex: /home/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    # ex: /home/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # ex: /home/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=255)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=255)
    address = models.CharField(blank=True, max_length=255)
    phone = models.CharField(blank=True, max_length=255)
    fax = models.CharField(blank=True, max_length=255)
    email = models.CharField(blank=True, max_length=255)
    smtpserver = models.CharField(blank=True, max_length=255)
    smtpemail = models.CharField(blank=True, max_length=255)
    smtppassword = models.CharField(blank=True, max_length=255)
    smtpport = models.CharField(blank=True, max_length=255)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=255)
    instagram = models.CharField(blank=True, max_length=255)
    twitter = models.CharField(blank=True, max_length=255)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(blank=True, max_length=70)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': TextInput(attrs={'class': 'controls', 'placeholder': 'Full Name'}),
            'email': TextInput(attrs={'class': 'controls', 'placeholder': 'Email Address'}),
            'subject': TextInput(attrs={'class': 'controls', 'placeholder': 'Subject'}),
            'message': Textarea(attrs={'class': 'controls', 'placeholder': 'Message'}),
        }


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=70)
    country = models.CharField(blank=True, max_length=70)
    image = models.ImageField(blank=True, upload_to='images/users')

    def user_name(self):
        return self.user.first_name + ' ' + self.user.last_name + ' [ ' + self.user.username + ' ] '

    def image_tag(self):
        return mark_safe('<img src="{}" height="50" />'.format(self.image.url))
    image_tag.short_description = 'Image'


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'address', 'city', 'country', 'image']


class Faq(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    orderNumber = models.IntegerField()
    question = models.CharField(max_length=255)
    answer = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

user/models.py
from django.db import models

# Create your models here.
from django.forms import ModelForm
from house.models import House, Images


class HouseImageForm(ModelForm):
    class Meta:
        model = Images
        fields = ['title', 'image']

user/forms.py
from ckeditor.widgets import CKEditorWidget
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from django.forms import TextInput, EmailInput, forms, Select, FileInput
from django import forms
from home.models import UserProfile
from house.models import House, Category


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')
        widgets = {
            'username': TextInput(attrs={'class': 'input', 'placeholder': 'username'}),
            'email': EmailInput(attrs={'class': 'input', 'placeholder': 'email'}),
            'first_name': TextInput(attrs={'class': 'input', 'placeholder': 'first_name'}),
            'last_name': TextInput(attrs={'class': 'input', 'placeholder': 'last_name'}),
        }


CITY = [
    ('Istanbul', 'Istanbul'),
    ('Ankara', 'Ankara'),
    ('Izmir', 'Izmir'),
]


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'address', 'city', 'country', 'image')
        widgets = {
            'phone': TextInput(attrs={'class': 'input', 'placeholder': 'phone'}),
            'address': TextInput(attrs={'class': 'input', 'placeholder': 'address'}),
            'city': Select(attrs={'class': 'input', 'placeholder': 'city'}, choices=CITY),
            'country': TextInput(attrs={'class': 'input', 'placeholder': 'country'}),
            'image': FileInput(attrs={'class': 'input', 'placeholder': 'image'}),
        }


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'address', 'city', 'country', 'image')
        widgets = {
            'phone': TextInput(attrs={'class': 'input', 'placeholder': 'phone'}),
            'address': TextInput(attrs={'class': 'input', 'placeholder': 'address'}),
            'city': Select(attrs={'class': 'input', 'placeholder': 'city'}, choices=CITY),
            'country': TextInput(attrs={'class': 'input', 'placeholder': 'country'}),
            'image': FileInput(attrs={'class': 'input', 'placeholder': 'image'}),
        }


OPTIONS = [
    ('True', 'Evet'),
    ('False', 'Hayır'),
]


class HouseForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=False)
    status = forms.ChoiceField(required=True, choices=OPTIONS)
    furnished = forms.ChoiceField(required=True, choices=OPTIONS)
    balconied = forms.ChoiceField(required=True, choices=OPTIONS)
    withintheSite = forms.ChoiceField(required=True, choices=OPTIONS)
    detail = forms.CharField(widget=CKEditorWidget())
    image = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = House
        fields = ['category', 'title', 'keywords', 'description', 'slug', 'image',
                  'rent', 'detail', 'status', 'area', 'location',
                  'room', 'buildingFloor', 'floorLocation', 'furnished', 'balconied', 'heating', 'withintheSite',
                  'fromWho']

user/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

from home.models import UserProfile
from house.models import Category, Comment, House, Images
from user.forms import UserUpdateForm, ProfileUpdateForm, HouseForm
from user.models import HouseImageForm

def index(request):
    category = Category.objects.all()
    current_user = request.user
    profile = UserProfile.objects.get(user_id=current_user)
    context = {'category': category,
               'profile': profile}
    return render(request, 'user_profile.html', context)


def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your account has been updated!')
            return redirect('/user')
    else:
        category = Category.objects.all()
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.userprofile)
        context = {'category': category,
                   'user_form': user_form,
                   'profile_form': profile_form}
        return render(request, 'user_update.html', context)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated!')
            return HttpResponseRedirect('/user')
        else:
            messages.error(request, 'Please correct the error below.<br>' + str(form.errors))
            return HttpResponseRedirect('/user/password')
    else:
        category = Category.objects.all()
        form = PasswordChangeForm(request.user)
        return render(request, 'change_password.html', {
            'form': form, 'category': category})


@login_required(login_url='/login')
def comments(request):
    category = Category.objects.all()
    current_user = request.user
    comments = Comment.objects.filter(user_id=current_user)
    context = {'category': category,
               'comments': comments}
    return render(request, 'user_comments.html', context)


@login_required(login_url='/login')
def delete_comment(request, id):
    current_user = request.user
    Comment.objects.filter(id=id, user_id=current_user).delete()
    messages.error(request, 'Comment Deleted...')
    return HttpResponseRedirect('/user/comments')


@login_required(login_url='/login')
def houses(request):
    category = Category.objects.all()
    current_user = request.user
    house = House.objects.filter(user_id=current_user.id)
    context = {'category': category,
               'house': house}
    return render(request, 'user_houses.html', context)


@login_required(login_url='/login')
def addhouse(request):
    if request.method == 'POST':
        form = HouseForm(request.POST, request.FILES)
        if form.is_valid():
            current_user = request.user
            data = House()
            data.user_id = current_user.id
            data.title = form.cleaned_data['title']
            data.category = form.cleaned_data['category']
            data.keywords = form.cleaned_data['keywords']
            data.description = form.cleaned_data['description']
            data.slug = form.cleaned_data['slug']
            data.image = form.cleaned_data['image']
            data.rent = form.cleaned_data['rent']
            data.detail = form.cleaned_data['detail']
            data.status = 'False'
            data.area = form.cleaned_data['area']
            data.location = form.cleaned_data['location']
            data.room = form.cleaned_data['room']
            data.buildingFloor = form.cleaned_data['buildingFloor']
            data.floorLocation = form.cleaned_data['floorLocation']
            data.furnished = form.cleaned_data['furnished']
            data.balconied = form.cleaned_data['balconied']
            data.heating = form.cleaned_data['heating']
            data.withintheSite = form.cleaned_data['withintheSite']
            data.fromWho = form.cleaned_data['fromWho']
            data.save()
            messages.success(request, 'Your house added successfully!')
            return HttpResponseRedirect('/user/houses')
        else:
            messages.success(request, 'Your form error! :' + str(form.errors))
            return HttpResponseRedirect('/user/addhouse')
    else:
        category = Category.objects.all()
        form = HouseForm()
        context = {'category': category,
                   'form': form}
        return render(request, 'user_addhouse.html', context)


@login_required(login_url='/login')
def edithouse(request, id):
    house = House.objects.get(id=id)
    if request.method == 'POST':
        form = HouseForm(request.POST, request.FILES, instance=house)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your house updated successfully!')
            return HttpResponseRedirect('/user/houses')
        else:
            messages.success(request, 'Your form error! :' + str(form.errors))
            return HttpResponseRedirect('/user/edithouse/')
    else:
        category = Category.objects.all()
        form = HouseForm(instance=house)
        context = {'category': category,
                   'form': form}
        return render(request, 'user_addhouse.html', context)


@login_required(login_url='/login')
def deletehouse(request, id):
    current_user = request.user
    House.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'Your house deleted successfully!')
    return HttpResponseRedirect('/user/houses')


def houseaddimage(request, id):
    if request.method == 'POST':
        lasturl = request.META.get('HTTP_REFERER')
        form = HouseImageForm(request.POST, request.FILES)
        if form.is_valid():
            data = Images()
            data.title = form.cleaned_data['title']
            data.house_id = id
            data.image = form.cleaned_data['image']
            data.save()
            messages.success(request, 'Your image has been successfully uploaded!')
            return HttpResponseRedirect(lasturl)
        else:
            messages.warning(request, 'Form Error :' + str(form.errors))
            return HttpResponseRedirect(lasturl)
    else:
        house = House.objects.get(id=id)
        images = Images.objects.filter(house_id=id)
        form = HouseImageForm()
        context = {
            'house': house,
            'images': images,
            'form': form
        }
        return render(request, 'house_gallery.html', context)

user/templates/change_password.html
{% extends "homebase.html" %}

{% block title %} Change User Password {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block head %}
    <link rel="shortcut icon" type="text/x-icon" href="{{ setting.icon.url }}" >
{% endblock %}
{% block content %}

    <!-- full Title -->
    <div class="full-title">
        <div class="container">
            <!-- Page Heading/Breadcrumbs -->
            <h1 class="mt-4 mb-3"></h1>
            <div class="breadcrumb-main">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="/">Home</a>
                    </li>
                    <li class="breadcrumb-item active"></li>
                </ol>
            </div>
        </div>
    </div>

    <!-- Page Content -->
    <div class="container">
        <div>
            <div class="row">
                {% include 'user_panel.html' %}
                <div class="col-lg-9 mb-4">
                    <div class="card h-80">
                        <div class="card-header">
                            <div>CHANGE PASSWORD</div>
                        </div>
                        <ul class="list-group" style="padding: 25px 25px">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-{{ message.tags }}" role="alert">
                                        {{ message|safe}}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <form method="POST">
                                {% csrf_token %}
                                {% for field in form %}
                                    <p>
                                        {{ field.label_tag }}<br>
                                        {{ field }}
                                        {% if field.help_text %}
                                            <small style="color: grey">{{ field.help_text }}</small>
                                        {% endif %}
                                        {% for error in field.errors %}
                                            <p style="color: red">{{ error }}</p>
                                        {% endfor %}
                                    </p>
                                {% endfor %}
                                <button class="btn btn-sm btn-primary" type="submit">Save Changes</button>
                            </form>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container -->
{% endblock %}

user/templates/house_gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>House Gallery</title>
</head>
<body>
<h2>{{ house.title }}</h2>
<hr>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message|safe }}
        </div>
    {% endfor %}
{% endif %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="house_id" id="id_house_id" value="{{ house.id }}">
    <label for="id_title">Title :</label>
    <input type="text" name="title" class="input" placeholder="title" maxlength="50" id="id_title">
    <label for="id_image">Image :</label>
    <input type="file" name="image" class="input" placeholder="image" accept="/*" id="id_image">
    <button class="btn btn-sm btn-primary" type="submit">Upload Image</button>
</form>
<hr>
<h4>Uploaded Images</h4>
{% for rs in images %}
    <img src="{{ rs.image.url }}" height="200" alt="">
{% endfor %}
</body>
</html>

user/templates/user_addhouse.html
{% extends "homebase.html" %}

{% block title %} Add House {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block head %}
    <link rel="shortcut icon" type="text/x-icon" href="{{ setting.icon.url }}" >
    {% load static %}
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}
{% block content %}

    <!-- full Title -->
    <div class="full-title">
        <div class="container">
            <!-- Page Heading/Breadcrumbs -->
            <h1 class="mt-4 mb-3"></h1>
            <div class="breadcrumb-main">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="/">Home</a>
                    </li>
                    <li class="breadcrumb-item active"></li>
                </ol>
            </div>
        </div>
    </div>

    <!-- Page Content -->
    <div class="container">
        <div>
            <div class="row">
                {% include 'user_panel.html' %}
                <div class="col-lg-9 mb-4">
                    <div class="card h-80">
                        <div class="card-header">
                            <div>ADD HOUSE</div>
                        </div>
                        <ul class="list-group" style="padding: 25px 25px">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-{{ message.tags }}" role="alert">
                                        {{ message|safe }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <fieldset class="form-group">
                                    {{form.media}}
                                    {{ form.as_p }}
                                </fieldset>
                                <div class="form-group">
                                    <button class="btn btn-sm btn-primary" type="submit">Save</button>
                                </div>
                            </form>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container -->
{% endblock %}

user/templates/user_comments.html
{% extends "homebase.html" %}

{% block title %} Comments {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block head %}
    <link rel="shortcut icon" type="text/x-icon" href="{{ setting.icon.url }}" >
{% endblock %}
{% block content %}

    <!-- full Title -->
    <div class="full-title">
        <div class="container">
            <h1 class="mt-4 mb-3"></h1>
            <div class="breadcrumb-main">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="/">Home</a>
                    </li>
                    <li class="breadcrumb-item active"></li>
                </ol>
            </div>
        </div>
    </div>
    <div class="container">
        <div>
            <div class="row">
                {% include 'user_panel.html' %}
                <div class="col-lg-9 mb-4">
                    <div class="card h-80">
                        <div class="card-header">
                            <div>COMMENTS</div>
                        </div>
                        <ul class="list-group" style="padding: 25px 25px">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-{{ message.tags }}" role="alert">
                                        {{ message|safe}}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <table>
                                <tr>
                                    <th>House</th>
                                    <th>Subject</th>
                                    <th>Comment</th>
                                    <th>Status</th>
                                    <th>Date</th>
                                    <th></th>
                                </tr>
                                {% for rs in comments %}
                                    <tr>
                                        <td>
                                            <a href="/house/{{ rs.house_id }}/{{ rs.house.slug }}">{{ rs.house.title }}</a>
                                        </td>
                                        <td>{{rs.subject}}</td>
                                        <td>{{rs.comment}}</td>
                                        <td>{{rs.status}}</td>
                                        <td>{{rs.create_at}}</td>
                                        <td>
                                            <a class="btn btn-sm btn-primary" href="/user/delete_comment/{{ rs.id }}" onclick="return confirm('Will be delete ! Are you sure?')">Delete</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

user/templates/user_houses.html
{% extends "homebase.html" %}

{% block title %} User Houses {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block head %}
    <link rel="shortcut icon" type="text/x-icon" href="{{ setting.icon.url }}" >
{% endblock %}
{% block content %}

    <!-- full Title -->
    <div class="full-title">
        <div class="container">
            <h1 class="mt-4 mb-3"></h1>
            <div class="breadcrumb-main">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="/">Home</a>
                    </li>
                    <li class="breadcrumb-item active"></li>
                </ol>
            </div>
        </div>
    </div>
    <div class="container">
        <div>
            <div class="row">
                {% include 'user_panel.html' %}
                <div class="col-lg-9 mb-4">
                    <div class="card h-80">
                        <div class="card-header">
                            <div>USER HOUSES</div>
                        </div>
                        <ul class="list-group" style="padding: 25px 25px">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-{{ message.tags }}" role="alert">
                                        {{ message|safe}}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <table>
                                <tr>
                                    <th>Image</th>
                                    <th>House</th>
                                    <th>Category</th>
                                    <th>Gallery</th>
                                    <th>Rent</th>
                                    <th>Status</th>
                                </tr>
                                {% for rs in house %}
                                    <tr>
                                        <td>
                                            <a href="/house/{{ rs.id }}/{{ rs.slug }}"><img src="{{ rs.image.url }}" style="height: 30px;"></a>
                                        </td>
                                        <td>
                                            <a href="/house/{{ rs.id }}/{{ rs.slug }}">{{ rs.title }}</a>
                                        </td>
                                        <td>{{rs.category}}</td>
                                        <td>
                                            <a href="javascript:;" onclick="window.open('/user/houseaddimage/{{ rs.id }}', 'gallery', 'height=600,width=800,top=50,left=150')">Gallery</a>
                                        </td>
                                        <td>{{rs.rent}}</td>
                                        <td>{{rs.status}}</td>
                                        <td>
                                            <a class="btn btn-sm btn-primary" href="/user/edithouse/{{ rs.id }}">Edit</a>
                                        </td>
                                        <td>
                                            <a class="btn btn-sm btn-primary" href="/user/deletehouse/{{ rs.id }}" onclick="return confirm('Will be delete ! Are you sure?')">Delete</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                         <div><a class="btn btn-sm btn-primary" href="/user/addhouse/">ADD HOUSE</a></div>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

user/templates/user_panel.html
<div class="col-lg-3 mb-4">
    <div class="card-header">
        <div>USER PANEL</div>
    </div>
    <div class="card h-80">
        <ul class="list-group">
            <li class="list-group-item"><a href="/user">User Profile</a></li>
            <li class="list-group-item"><a href="/user/houses">My Houses</a></li>
            <li class="list-group-item"><a href="/user/comments">My Comments</a></li>
            <li class="list-group-item"><a href="/logout">Logout</a></li>
        </ul>
    </div>
</div>